# Reshaping and transposing

In [1]:
import numpy as np

In [6]:
np.random.seed(7)
arr = np.random.randint(10,size=(2,3))
arr

array([[4, 9, 6],
       [3, 3, 7]])

In [10]:
np.random.seed(8)
arr2 = np.random.randint(10,size=(2,3,3))
arr2

array([[[3, 4, 1],
        [9, 5, 8],
        [3, 8, 0]],

       [[5, 1, 3],
        [9, 2, 2],
        [6, 8, 9]]])

In [11]:
arr * arr2

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [12]:
#General Broadcasting Rules
#  When operating on two arrays, NumPy compares their shapes element-wise. It starts
#  with the trailing dimensions, and works its way forward. Two dimensions are compatible when
#          1. they are equal, or
#          2. one of them is 1

In [13]:
arr3 = arr.reshape(2,3,1)
arr3

array([[[4],
        [9],
        [6]],

       [[3],
        [3],
        [7]]])

In [14]:
arr3 * arr2

array([[[12, 16,  4],
        [81, 45, 72],
        [18, 48,  0]],

       [[15,  3,  9],
        [27,  6,  6],
        [42, 56, 63]]])

In [15]:
#now multiplication is possible due to reshaping

## Transpose

In [16]:
# switches the axis
arr.shape

(2, 3)

In [19]:
arr.T

array([[4, 3],
       [9, 3],
       [6, 7]])

In [21]:
arr.T.shape

(3, 2)