# NumPy

In [1]:
#why numpy
# 1. its fast
# 2. behind the scenes optimizations using c
# 3. vectorization usnig broadcasting(avoiding loops)
# 4. backbone of other python scientific packages


In [3]:
#what is covered/
# - most useful functions
# - numpy datatypes and attributes(ndarray)
# - creating arrays and matrices
# - viewing arrays and matrices
# - manupulating and comparing arrays
# - sorting arrays
# - use cases

In [4]:
import numpy as np

# datatypes and arrays

In [6]:
# numpy's main datatype is ndarray standing for n-dimentional array

In [7]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2.4,23.5],
             [2,3,2.3]])

In [11]:
a2

array([[ 1. ,  2.4, 23.5],
       [ 2. ,  3. ,  2.3]])

In [34]:
a3 = np.array([
                [[1,2,3   ],
                [2,4,5    ],
                [43,44,54 ]],
               [[12,223,45],
                [23,34,34 ],
                [23,23,4  ]]
                           ])

In [ ]:
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a3

array([[[  1,   2,   3],
        [  2,   4,   5],
        [ 43,  44,  54]],

       [[ 12, 223,  45],
        [ 23,  34,  34],
        [ 23,  23,   4]]])

In [27]:
a1.shape

(3,)

In [28]:
a2.shape

(2, 3)

In [29]:
a3.shape

(2,)

In [30]:
# ndim - number of dimentions

In [36]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [32]:
a4 = np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a4.shape


(2, 3, 3)

### whatever our data is it is converted into numbers and then machchine learning algo finds patterns in it

In [37]:
#dtype

a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [38]:
#size - number of elements

a1.size, a2.size, a3.size

(3, 6, 18)

In [39]:
#type

type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### note all are of the type ndarray

In [45]:
#creating a numpy dataframe from numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1     2
0  1.0  2.4  23.5
1  2.0  3.0   2.3