## comparison operators

In [1]:
import numpy as np

In [5]:
a1 = np.random.randint(10,size = (3))
a2 = np.random.randint(10,size = (3,3))
a1,a2

(array([8, 2, 9]),
 array([[0, 6, 7],
        [3, 4, 6],
        [1, 8, 4]]))

In [6]:
a1>a2

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [7]:
# sorting arrays

In [16]:
a2 = np.random.randint(10,size = (3,5))
a2

array([[5, 1, 9, 7, 9],
       [8, 8, 5, 7, 4],
       [8, 6, 7, 9, 8]])

In [17]:
np.sort(a2)

array([[1, 5, 7, 9, 9],
       [4, 5, 7, 8, 8],
       [6, 7, 8, 8, 9]])

In [18]:
#sorted in each axis

In [19]:
np.argsort(a2)

array([[1, 0, 3, 2, 4],
       [4, 2, 3, 0, 1],
       [1, 2, 0, 4, 3]], dtype=int64)

In [20]:
#returning the index of matrix or position not values

In [25]:
#now if we wanted to know the column wise min max index


In [26]:
a2

array([[5, 1, 9, 7, 9],
       [8, 8, 5, 7, 4],
       [8, 6, 7, 9, 8]])

In [22]:
np.argmax(a2,axis=0)
#this tells in each COLUMN which index is the max

array([1, 1, 0, 2, 0], dtype=int64)

In [23]:
np.argmax(a2,axis=1)
##this tells in each Row which index is the max

array([2, 0, 3], dtype=int64)