# creating arrays

### press shift + tab while inside function to see its definition

In [1]:
import numpy as np

In [2]:
ones  = np.ones((3,4))

In [ ]:
# this function generates an array with ones; acting as place-holder

In [ ]:
# 3 rows and 4 columns

In [3]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
ones_2 = np.ones((3,4,2))

In [5]:
ones_2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [6]:
#another such function zeros()

In [8]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#range array

In [ ]:
# arange()

In [10]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
# random.randint()

In [15]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[9, 1, 2, 7, 1],
       [4, 5, 5, 9, 5],
       [1, 9, 0, 8, 8]])

In [16]:
# note the range is exclusive (0 and 10 not included) for more: shift+tab

In [17]:
# random()

In [ ]:
#as we can see it returns rand num b/w 0 and 1; parameter: size

In [18]:
random_arr_2 = np.random.random((4,2))
random_arr_2

array([[0.84414095, 0.33255131],
       [0.63001281, 0.18536743],
       [0.87702955, 0.81614   ],
       [0.42839969, 0.46020137]])

## note: when numpy generates random num; they are pseudo-random numbers

In [19]:
# note : axis-0 : rows, axis-1:columns

In [22]:
random_arr_3 = np.random.rand(3,5)
random_arr_3

array([[0.6198813 , 0.14654446, 0.87802145, 0.06671868, 0.22449067],
       [0.95368408, 0.19452607, 0.93668849, 0.16667588, 0.50929872],
       [0.36596266, 0.81061116, 0.15467784, 0.0954003 , 0.91197348]])

In [23]:
# difference b/w rand() and random()

# so far what i found in brief:
#    numpy.random.randn generates samples from the **normal distribution**, 
#    while numpy.random.rand from **uniform** (in range [0,1)).
