# Dot product example

In [5]:
import numpy as np
import pandas as pd

In [2]:
#number of jars sold

In [3]:
np.random.seed(0)
sales_amounts = np.random.randint(10, size=(5,3))
sales_amounts

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [4]:
#create weekly sales dataframe

In [6]:
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["mon","tue","wed","thu","fri"],
                           columns=["Almond butter","Peanut butter","cashew butter"])
weekly_sales

Almond butter  Peanut butter  cashew butter
mon              5              0              3
tue              3              7              9
wed              3              5              2
thu              4              7              6
fri              8              8              1

In [7]:
# create prices array

In [8]:
prices = np.array([10,8,10])
prices

array([10,  8, 10])

In [9]:
# create butter prices dataframe

In [12]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond butter","Peanut butter","cashew butter"])
butter_prices

Almond butter  Peanut butter  cashew butter
Price             10              8             10

In [14]:
weekly_sales, butter_prices

(     Almond butter  Peanut butter  cashew butter
 mon              5              0              3
 tue              3              7              9
 wed              3              5              2
 thu              4              7              6
 fri              8              8              1,
        Almond butter  Peanut butter  cashew butter
 Price             10              8             10)

In [18]:

total_sales = prices.dot(sales_amounts.T)
total_sales

array([ 80, 176,  90, 156, 154])

In [19]:
# create daily_sales

In [20]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [21]:
# we dot producted dataframes not arrays here

In [22]:
daily_sales

mon  tue  wed  thu  fri
Price   80  176   90  156  154

In [23]:
# now we have to put the daily sales in our weekly sale dataframe

In [25]:
# this doesnt work as daily sales isnt in right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Wrong number of items passed 5, placement implies 1

In [26]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  cashew butter  Total ($)
mon              5              0              3         80
tue              3              7              9        176
wed              3              5              2         90
thu              4              7              6        156
fri              8              8              1        154