In [3]:
import numpy as np

In [4]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [5]:
mat1 

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [6]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [7]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [8]:
#error is happening as for dot prod to happen (5x3) & (5x3) cant happen 
# it should of the form (axb)(bxc) ; a and c can be anything; result will be axc

In [9]:
#so this is where the application of transpose come

In [12]:
mat1 = mat1.T

In [16]:
#now
mat3 = np.dot(mat1,mat2)
mat3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [17]:
mat3.shape

(3, 3)