# viewing arrays and matrices

In [2]:
# let we have to find unique num in our array

In [3]:
import numpy as np

In [5]:
random_arr = np.random.randint(10,size=(5,3))
random_arr

array([[2, 6, 3],
       [2, 3, 2],
       [3, 9, 5],
       [0, 3, 9],
       [7, 4, 9]])

In [ ]:
# unique() ; gives sorted distinct/unique elements of the arr

In [6]:
np.unique(random_arr)

array([0, 2, 3, 4, 5, 6, 7, 9])

In [7]:
# terminology : 1-D arr : called vector
#               2...n-D arr : matrix

## viewing arr

In [14]:
np.random.seed(7)
arr = np.random.randint(20, size = (4,3,3))
arr

array([[[15,  4,  3],
        [19,  7, 14],
        [ 8, 14, 10]],

       [[ 8,  7,  6],
        [ 4, 16,  7],
        [12,  0, 11]],

       [[ 6, 19, 12],
        [ 5, 16,  0],
        [ 2,  9, 14]],

       [[ 6,  4, 14],
        [ 9,  3,  3],
        [ 8, 19, 16]]])

In [19]:
arr[:3,:3,:2]

array([[[15,  4],
        [19,  7],
        [ 8, 14]],

       [[ 8,  7],
        [ 4, 16],
        [12,  0]],

       [[ 6, 19],
        [ 5, 16],
        [ 2,  9]]])

In [20]:
#this is telling to display 3 lists out of 4, 3 rows of each of them , 2 colums of each those rows

In [22]:
np.random.seed(7)
arr_2 = np.random.randint(20, size = (2,3,3,3))
arr_2

array([[[[15,  4,  3],
         [19,  7, 14],
         [ 8, 14, 10]],

        [[ 8,  7,  6],
         [ 4, 16,  7],
         [12,  0, 11]],

        [[ 6, 19, 12],
         [ 5, 16,  0],
         [ 2,  9, 14]]],


       [[[ 6,  4, 14],
         [ 9,  3,  3],
         [ 8, 19, 16]],

        [[ 1,  0, 16],
         [12,  7, 10],
         [ 9,  3,  0]],

        [[ 7,  0,  4],
         [ 3,  1,  3],
         [ 1, 19,  4]]]])

In [24]:
arr_2.shape, arr_2.ndim

((2, 3, 3, 3), 4)

In [ ]:
#using slices to display differnt parts

In [44]:
arr_2[slice(2),:1,:2,:3]

array([[[[15,  4,  3],
         [19,  7, 14]]],


       [[[ 6,  4, 14],
         [ 9,  3,  3]]]])

In [45]:
arr_2[:2,:1,:2,:3]

array([[[[15,  4,  3],
         [19,  7, 14]]],


       [[[ 6,  4, 14],
         [ 9,  3,  3]]]])